---
#- name: Install the  repo PostgreSQL CentOS
#  yum: name=https://download.postgresql.org/pub/repos/yum/{{pg_version}}/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm state=present
#  when: ansible_distribution == 'CentOS' 
#  tags:
#    - postgresql

- name:  Install the  repo PostgreSQL RedHat
  yum: name=https://download.postgresql.org/pub/repos/yum/{{pg_version}}/redhat/rhel-7-x86_64/pgdg-redhat11-11-2.noarch.rpm state=present
 # when: ansible_distribution == 'RedHat'
  tags:
    - postgresql  

- name: Install Postgres
  yum: name={{ item }} state=present
  with_items:
    - postgresql{{ version_pkg }}-server
    - python-psycopg2
  tags:
    - postgresql

- name: Create data directory Postgressql
  file: path=/pgsql/{{ pg_version }}/data state=directory  owner=postgres group=postgres
  tags:
    - postgresql

- name: Config PGSQL_HOME
  template: src=postgresqlenv.j2 dest=/etc/profile.d/postgresql.sh  owner=root group=root mode=0644
  tags:
    - postgres

- name: Initial data Postgresql
  command: su - postgres -c "/usr/pgsql-{{ pg_version }}/bin/initdb -D /pgsql/{{ pg_version }}/data"
  #become: true
  #become_user: postgres
  tags:
    - postgresql

- name: Template service postgresql
  template: src=postgresql.service.j2 dest=/usr/lib/systemd/system/postgresql-{{ pg_version }}.service
  notify: reload systemd
  tags:
    - postgresql

- name: Start service Postgresql
  service: name=postgresql-{{ pg_version }} state=started enabled=yes
  tags:
    - postgresql
